---
title: "JEZ_Analysis"
author: "Kaija Gahm"
date: "4/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
source("libraries.R")
```

# Load data
```{r}
# Lab and wild
load("data/outputs/dat3_nonas.Rda")
load("data/outputs/wild_nonas.Rda")

# Oviposition dates
load("data/outputs/wild_dates.Rda")
head(wild_dates)
```

# Calculate developmental rates (stages/day)
## Wild
### Calculate
```{r}
wild <- wild_nonas %>%
  mutate(devrate = (gs-1)/as.numeric((burst_date-ovip_date)))
```

## Lab
### Bind oviposition dates
```{r}
lab <- wild_dates %>%
  select(pond, ovip_date) %>%
  distinct() %>%
  right_join(dat3_nonas, by = "pond")
```
### Calculate
```{r}
lab <- lab %>%
  mutate(devrate = (gs-1)/as.numeric((burst_date-ovip_date)))

head(lab)
```

# Do dev rates differ between Tx?
## Prepare data
```{r}
labdev <- lab %>% select(pond, clutch, tadpole, treatment, devrate)
wilddev <- wild %>% select(pond, tadpole, devrate)

dev <- bind_rows(labdev, wilddev) %>%
  mutate(treatment = case_when(is.na(treatment) ~ "Wild",
                               TRUE ~ as.character(treatment))) %>%
  mutate(treatment = factor(treatment))
```

## ANOVA
```{r}
mod <- lm(devrate ~ treatment, data = dev)
summary(mod)
```

# Does performance differ between Tx?
```{r}
load("data/outputs/dat3_nonas.Rda")
head(dat3_nonas)

# Unstandardized
performance_mod_lab <- lmer(sline_speed_mm_s ~ mass_at_stage*treatment + gs*treatment + PC2 + T_initial + (1|pond/clutch/tadpole), data = dat3_nonas)
summary(performance_mod_lab)

# Standardized
load("data/outputs/dat3_nonas_std.Rda")
head(dat3_nonas_std)
performance_mod_lab_std <- lmer(sline_speed_mm_s ~ mass_at_stage*treatment + gs*treatment + PC2 + T_initial + (1|pond/clutch/tadpole), data = dat3_nonas_std)
summary(performance_mod_lab_std)
```

