# Examples of different loess smooths
load("matlabplots.Rda")
allplots <- unlist(matlabplots, recursive = F)

allplots[[1]]
allplots[[2]]
allplots[[3]]
allplots[[4]]
allplots[[5]]
allplots[[6]]
allplots[[7]]
allplots[[8]]
allplots[[9]]
allplots[[10]]
allplots[[11]]
allplots[[12]]
allplots[[13]]
allplots[[14]]
allplots[[15]]
allplots[[16]]
allplots[[17]]
allplots[[18]]
allplots[[19]]
allplots[[20]]
allplots[[21]]
allplots[[22]]
allplots[[23]]
allplots[[24]]
allplots[[25]]
allplots[[26]]
allplots[[27]]
allplots[[28]]
allplots[[29]]
allplots[[30]]
allplots[[31]]
allplots[[32]]
allplots[[33]]
allplots[[34]]
allplots[[35]]
allplots[[36]]
allplots[[37]]

